<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net481</TargetFramework>
		<Nullable>disable</Nullable>
		<AssemblyName>GamepadSupport</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Analyzers" />
		<PackageReference Include="BepInEx.Core" />
		<PackageReference Include="BepInEx.PluginInfoProps" />
		<PackageReference Include="UnityEngine.Modules" />
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<ItemGroup>
			<BuildOutputs Include="$(TargetPath)" />
			<!-- I have absolutely no idea why 4.6.1 is the special one that has the working DLL. -->
			<BuildOutputs Include="$(MSBuildExtensionsPath)\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\netstandard.dll" />
		</ItemGroup>
		<Copy SourceFiles="@(BuildOutputs)" DestinationFolder="C:\Program Files (x86)\Steam\steamapps\common\Katamari Damacy REROLL\BepInEx\plugins" />
	</Target>

</Project>
