<Project>
	<PropertyGroup>
		<VersionPrefix>1.1.0</VersionPrefix>
		<LangVersion>latest</LangVersion>
		<RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableNETAnalyzers>True</EnableNETAnalyzers>
		<Nullable>enable</Nullable>
		<TargetFramework>net35</TargetFramework>
		<OutputPath>$(SolutionDir)/out</OutputPath>
		<UseCommonOutputDirectory>true</UseCommonOutputDirectory>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

	<Target Name="ReferencePatchUtils" BeforeTargets="CoreCompile">
		<PropertyGroup>
			<IncludeUtils Condition="%(PackageReference.Identity) == 'UnityEngine.Modules'">1</IncludeUtils>
		</PropertyGroup>

		<ItemGroup Condition="$(IncludeUtils) == 1">
			<Compile Include="$(SolutionDir)/PatchUtils.cs" />
		</ItemGroup>
	</Target>
</Project>