<Project>
	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableNETAnalyzers>True</EnableNETAnalyzers>
		<Nullable>enable</Nullable>
		<TargetFramework>net35</TargetFramework>
	</PropertyGroup>
</Project>