<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net45</TargetFramework>
		<Nullable>enable</Nullable>
		<AssemblyName>KatamariDama60</AssemblyName>
		<LangVersion>latest</LangVersion>
		<RestoreAdditionalProjectSources>
			https://api.nuget.org/v3/index.json;
			https://nuget.bepinex.dev/v3/index.json
		</RestoreAdditionalProjectSources>
		<RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
		<PackageReference Include="BepInEx.Core" Version="5.*" />
		<PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
		<PackageReference Include="NETStandard.Library" Version="2.0.3" IncludeAssets="all" />
		<PackageReference Include="UnityEngine.Modules" Version="2018.1.9" IncludeAssets="compile" />
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.2" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Katamari">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Katamari Damacy REROLL\katamari_Data\Managed\Assembly-CSharp.dll</HintPath>
			<Private>False</Private>
			<Publicize>True</Publicize>
		</Reference>
		<Reference Include="firstpass">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Katamari Damacy REROLL\katamari_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="copy &quot;$(TargetPath)&quot; &quot;C:\Program Files (x86)\Steam\steamapps\common\Katamari Damacy REROLL\BepInEx\Plugins&quot;" />
	</Target>
</Project>
