<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net35</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Analyzers" />
		<PackageReference Include="BepInEx.Core" />
		<PackageReference Include="BepInEx.PluginInfoProps" />
		<PackageReference Include="UnityEngine.Modules" />
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="C:\Program Files (x86)\Steam\steamapps\common\Katamari Damacy REROLL\BepInEx\plugins" />
	</Target>

</Project>
