<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<ProjectReference Include="..\QualityOfLife\QualityOfLife.csproj" />
		<ProjectReference Include="..\FramerateUncap\FramerateUncap.csproj" />
		<ProjectReference Include="..\GamepadSupport\GamepadSupport.csproj" />
		<ProjectReference Include="..\RenderDocHook\RenderDocHook.csproj" />
		<ProjectReference Include="..\SingleplayerCousins\SingleplayerCousins.csproj" />
	</ItemGroup>
</Project>