<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="AssimpNet" />
		<PackageReference Include="BepInEx.Analyzers" />
		<PackageReference Include="BepInEx.Core" />
		<PackageReference Include="BepInEx.PluginInfoProps" />
		<PackageReference Include="IsExternalInit" />
		<PackageReference Include="UnityEngine.Modules" />
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" />
	</ItemGroup>
	
	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="Exists($(GameDir))">
		<!-- TODO: Copy AssimpNet DLLs to game folder -->
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(GameDir)\BepInEx\plugins" />
	</Target>
</Project>
