name: Build
on:
  - push
  - workflow_dispatch
jobs:
  build:

    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true

    steps:
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          architecture: x64
      
      - uses: actions/checkout@v6

      - run: dotnet publish -c Release

      - uses: actions/upload-artifact@v6
        with:
          name: release
          path: |
            out/publish/FramerateUncap.dll
            out/publish/GamepadSupport.dll
            out/publish/GraphicalEnhancements.dll
            out/publish/QualityOfLife.dll
            out/publish/SingleplayerCousins.dll

            out/publish/AssimpNet.dll
            out/runtimes/win-x64/native/assimp.dll
