name: Build
on:
  - push
  - workflow_dispatch
jobs:
  build:

    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true

    steps:
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          architecture: x64

      - uses: ilammy/setup-nasm@v1

      - run: rustup override set nightly

      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - run: dotnet publish -c Release

      - name: Build Rust component
        run: cargo build --release --no-default-features --manifest-path ./native-patches/Cargo.toml

      - name: Build CSteamworks replacement
        run: cargo build --release --no-default-features --manifest-path ./steamworks-wrapper/Cargo.toml

      - name: Assemble final directory structure
        run: |
          mkdir -p ./artifact/BepInEx/plugins
          mkdir -p ./artifact/katamari_Data/Plugins/runtimes/win-x64/native

          $managed = "FramerateUncap",
                     "GamepadSupport",
                     "GraphicalEnhancements",
                     "QualityOfLife",
                     "SingleplayerCousins",
                     "AssimpNet"

          foreach ($assembly in $managed) {
            cp ./out/publish/$assembly.dll ./artifact/BepInEx/plugins/
          }

          cp ./out/runtimes/win-x64/native/assimp.dll ./artifact/katamari_Data/Plugins/runtimes/win-x64/native/

          cp ./native-patches/target/release/katamari_ffi.dll ./artifact/katamari_Data/Plugins/
          cp ./steamworks-wrapper/target/release/CSteamworks.dll ./artifact/katamari_Data/Plugins/
          # TODO: SDL3.dll
          # TODO: New steam_api64.dll

      - uses: actions/upload-artifact@v6
        with:
          name: release
          path: ./artifact/
