name: Build
on:
  - push
  - workflow_dispatch
jobs:
  build:

    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true

    steps:
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          architecture: x64
      
      - uses: actions/checkout@v6

      - run: dotnet publish -c Release

      - name: Assemble final directory structure
        run: |
          mkdir -p ./artifact/BepInEx/plugins
          mkdir -p ./artifact/katamari_Data/Plugins/runtimes/win-x64/native

          $managed = "FramerateUncap",
                     "GamepadSupport",
                     "GraphicalEnhancements",
                     "QualityOfLife",
                     "SingleplayerCousins",
                     "AssimpNet"

          foreach ($assembly in $managed) {
            cp ./out/publish/$assembly.dll ./artifact/BepInEx/plugins/
          }

          cp ./out/runtimes/win-x64/native/assimp.dll ./artifact/katamari_Data/Plugins/runtimes/win-x64/native/
          # TODO: SDL3.dll
          # TODO: Make git submodules for the two Rust crates and include them in this

      - uses: actions/upload-artifact@v6
        with:
          name: release
          path: ./artifact/
